### ISSUE TITLE
How to get `key` for a custom renderer?

### ISSUE THREAD

**Issue by alari** [rexxars/commonmark-react-renderer#18]
Hi.

I want to write a custom renderer for Paragraph. So I'm beginning with quite a simple snippet:

```
const renderers = {
  Paragraph: React.createClass({

    render: function() {
      console.log("P", this.props)
      return (<p>{this.props.children}</p>)
    }
  })
}
```

The problem is that I can't get `key` property from props.
It shows no error for `p`, but if I have several children inside (e.g. 2 lines with `br` softbreak between), React says it needs a `key` in an array.

What should I do? Is it a bug or a feature? :)

Thanks!

**Comment by rexxars** [comment]
Sorry for super later reply, but I can't reproduce this... Children are already given keys by the time you received them in your custom renderer. If you are generating your own children in there you can assign them any keys you want, as long as they're unique within your element.

If you need access to the key for the paragraph, it is passed as the `nodeKey` property. If you need access to keys of the children, you can reach them at `props.children[childIndex].key`. It might be that this issue has resolved itself since may, too.

Happy to help if you have more questions.
