### ISSUE TITLE
Does not handle class-based React renderers

### ISSUE THREAD

**Issue by maxkferg** [rexxars/commonmark-react-renderer#22]
This package does not support ES6 Class-based renderers.
It would be nice, especially as these are becoming the norm.

**Comment by Yomguithereal** [comment]
What do you mean by this @maxkferg? Did it break when trying to register custom renderers using ES6 classes? Do you have an example of the issue?

**Comment by rexxars** [comment]
Seems to work just fine for me:

https://jsfiddle.net/tuvfax9p/1/

Uses a small class that extends `React.Component`. Ran through the Babel compiler (see bottom of Javascript part for the source). Will reopen if you can provide a failing example.

**Comment by maxkferg** [comment]
@rexxars

Yes, my code broke when I used a custom ES6 class renderer. The setup was very similar to the one you had on jsfiddle. I think your jsfiddle worked because you added that getHeader() wrapper function. I have replicated the error at https://jsfiddle.net/tuvfax9p/1/

We have already found a simple workaround (extending Component not React.Component). Maybe I was just doing something wrong. Check the jsfiddle and let me know.

**Comment by rexxars** [comment]
In the particular example, your code doesn't work because you defined renderers before MyHeading is actually defined. The reason why my example works is that functions in JS are hoisted to the top of the code, so when I call `getCustomHeader()`, it's available.

If you add a `console.log(renderers)` right after defining the object, you'll see that the value for `Heading` is undefined.

These examples are pretty contrived, but I'm 99.9% sure that commonmark-react-renderer works fine with ES5-style `React.createClass`, ES6-classes that extend `React.Component` as well as pure functions.

Hope you figure it out :)
